""" Update

Revision ID: 438f1037ca1d
Revises: 874beaca5870
Create Date: 2021-11-26 12:31:42.060086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438f1037ca1d'
down_revision = '874beaca5870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_check', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_check')
    # ### end Alembic commands ###
