"""Movie changes

Revision ID: 43a51edb7a71
Revises: 438f1037ca1d
Create Date: 2021-11-28 15:43:01.892998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43a51edb7a71'
down_revision = '438f1037ca1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movie_rating', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('movie_release_year', sa.Text(), nullable=True))
    op.drop_column('movie', 'movie_genre')
    op.drop_column('movie', 'movie_release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movie_release_date', sa.DATE(), nullable=True))
    op.add_column('movie', sa.Column('movie_genre', mysql.TEXT(), nullable=True))
    op.drop_column('movie', 'movie_release_year')
    op.drop_column('movie', 'movie_rating')
    # ### end Alembic commands ###
