"""actor in movie

Revision ID: b6a58bcbdf0f
Revises: 43a51edb7a71
Create Date: 2021-11-30 17:05:31.708746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a58bcbdf0f'
down_revision = '43a51edb7a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_in_movie',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], )
    )
    op.create_table('director_in_movie',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.director_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('director_in_movie')
    op.drop_table('actor_in_movie')
    # ### end Alembic commands ###
