"""drop column

Revision ID: f39ec4b910ea
Revises: b7e26dcb3acb
Create Date: 2021-11-24 15:32:53.499086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39ec4b910ea'
down_revision = 'b7e26dcb3acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'booking_date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('booking_date_time', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
